
# Project Configuration
project_id = "xnlzqsoujwsffoxhhybk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54323

[studio]
enabled = true
port = 54323

[functions.send-password-reset]
verify_jwt = false

[functions.send-password-reset.import_map]
imports = {}

[functions.process-email-queue]
verify_jwt = false

[functions.process-email-queue.import_map]
imports = {}

[functions.send-welcome-email]
verify_jwt = false

[functions.send-welcome-email.import_map]
imports = {}
