
# This file lists which secrets are required by which functions.
# When run locally with `supabase functions serve` you'll need to set the secrets in a .env file.
# When deployed to Supabase, you'll need to set the secrets in the dashboard.
# https://supabase.com/docs/guides/functions/secrets

[functions.send-password-reset]
verify_jwt = false

[functions.send-password-reset.import_map]
imports = {}

