# Project Configuration
project_id = "xnlzqsoujwsffoxhhybk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323